### ISSUE TITLE
How to Identify Continuous Model?

### ISSUE THREAD

**Issue by mzahana** [CPCLAB-UNIPI/SIPPY#15]
Hello.

Is there a way to convert a discrete model identified by sippy to continuous one?
Thanks.

**Comment by fpelagagge** [comment]
Hi, 
you could use the "harold" function "undiscretize". [https://harold.readthedocs.io/en/latest/generated/harold.undiscretize.html#harold.undiscretize
](https://harold.readthedocs.io/en/latest/generated/harold.undiscretize.html#harold.undiscretize
)
 You can refer to the documentation of that package for how to define the discrete system and convert it to continuous one.
[https://github.com/ilayn/harold](https://github.com/ilayn/harold
)

The python-control package does not have a discrete-to-continuous conversion function "d2c".

Hoping to have answered your questions.
Best.

**Comment by mzahana** [comment]
Thanks @fpelagagge for your answer. The `harold` did the job.
