### ISSUE TITLE
How to Select SS_p and SS_f?

### ISSUE THREAD

**Issue by mzahana** [CPCLAB-UNIPI/SIPPY#17]
Hello.

I would like to have a better understanding of what `SS_p` and `SS_f` are and how they affect the identification process. Is there a way to select reasonable values of them, based on the knowledge of the I/O data?

Thanks.

**Comment by CPCLAB-UNIPI** [comment]
Hi,

SS_p and SS_f are referred to as "past" and "future" horizons, respectively. Generally speaking:
1) The past horizon should be large enough that the effect of the initial condition has become irrelevant. This clearly depends on the settling time of your system.
2)  The future horizon should be in order of, at least, twice the expected model order.
To understand what they are, how they enter the identification algorithm, and further guidelines on their selection, I recommend you to read the subspace identification literature, and the N4SID original papers. 

Aside, please do not open an issues for a situation like where you would like to understand how an algorithm, publicly described in the scientific literature and textbooks, works. Please consider opening an issue when you identify a run-time error, an error in the results,  an unexpected behavior, etc.

Thank you. Best regards,
