### ISSUE TITLE
pip install git+https://github.com/CPCLAB-UNIPI/SIPPY.git result in requires a different Python Error

### ISSUE THREAD

**Issue by jamestjsp** [CPCLAB-UNIPI/SIPPY#26]
ERROR: Package 'sippy' requires a different Python: 3.6.12 not in '==2.7,>=3.5,<=3.7'

**Comment by CameronDevine** [comment]
The comma in the setuptools puthon_requires argument is equivalent to a logical and. For a workaround see https://stackoverflow.com/questions/44660448/using-python-requires-to-require-python-2-7-or-3-2

**Comment by CPCLAB-UNIPI** [comment]
Thanks for the notification. 
We have updated `setup.py` so that now it reads: ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<=3.7.*".
Please let us know if it solved the problem.

**Comment by Santh379** [comment]
I am facing the following error while installing SIPPY. 

ERROR: Package 'sippy' requires a different Python: 3.7.9 not in '!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<=3.7.*,>=2.7'

**Comment by CPCLAB-UNIPI** [comment]
Dear Santh379, 
sorry for the late response.
We have modified again the string of `python_requires` and it should now let you install SIPPY with python 3.7.9.

Please let us know if you are still facing problems.

Best, the SIPPY team
