### ISSUE TITLE
Most examples do not work

### ISSUE THREAD

**Issue by CameronDevine** [CPCLAB-UNIPI/SIPPY#3]
I attempted to run the examples, but I could only get the `SS.py` script to run. There appears to be a problem with the shape of one of the outputs of `lsim`. The error messages can be found here, https://travis-ci.org/CameronDevine/SIPPY/jobs/413816972

**Comment by don4get** [comment]
Same here, is there something I can do to help you solve these examples? 
`lsim` is not part of `control` but `control.matlab`. I made that move and then I got this error:
```
File "SIPPY/Examples/ARMAX_MIMO.py", line 121, in <module>
    err_outputH[0,:], Time, Xsim = cnt.lsim(H_sample1, err_inputH[0,:], Time)
ValueError: could not broadcast input array from shape (401,1) into shape (401)

**Comment by CameronDevine** [comment]
The following bit of code should fix the issue,

```python
import control as cnt
if not hasattr(cnt, 'lsim'):
   from control.matlab import lsim
   cnt.lsim = lsim
```

**Comment by willycamps** [comment]
> The following bit of code should fix the issue,
> 
> ```python
> import control as cnt
> if not hasattr(cnt, 'lsim'):
>    from control.matlab import lsim
>    cnt.lsim = lsim
> ```

It works perfect, thanks!

**Comment by CPCLAB-UNIPI** [comment]
Closing this issue due to recent merge.
