### ISSUE TITLE
 Setup script exited with Problem with the CMake installation

### ISSUE THREAD

**Issue by RuiAmorimSousa** [CPCLAB-UNIPI/SIPPY#41]
Hey! First of all good job with this project. It looks it as  a lot of potential. I am just having a problem with installing the setup.py file since this error is appearing: 
"error: Setup script exited with Problem with the CMake installation, aborting build. CMake executable is cmake"
Can you explain how to solve this? Tried to search about it but could not find anything.
Thanks

**Comment by RBdC** [comment]
Dear Rui Amorim Sousa,
sorry for the delay in our reply.
Did you manage to solve this issue in the meanwhile by your own?
Otherwise, try to uninstall and reinstall cmake package again.
This should solve your problem.
Let us know.
Best regards
SIPPY staff

**Comment by RuiAmorimSousa** [comment]
The problem was solved in the meantime. Thank you for the answer

**Comment by CPCLAB-UNIPI** [comment]
good to hear it!
