### ISSUE TITLE
How to install it through Anaconda?

### ISSUE THREAD

**Issue by Barzi2001** [CPCLAB-UNIPI/SIPPY#43]
Is there any way to install it through Anaconda (Windows 10)?

**Comment by RBdC** [comment]
Dear Barzi2001,
unfortunately, for the moment there is no "direct" way to install our SIPPY within Anaconda (e.g., via conda or via pip command).. we could work on this aspect in the next future !
The only way to install SIPPY now is by download the package from this github and then typing the following line:
python setup.py install
on your own Terminal or on the Anaconda Prompt, to gather all the required packages.
Note that, before running the installation, you need to move to the precise path containing the directory with SIPPY package and setup.py file located on your PC.
Best Regards
SIPPY Team
